"""
Project Z - ExpectedAttendance Model
Pre-computed daily workforce expectations per employee.

One row per employee per operational shift date.
Generated by the roster engine from shift assignments + department rules.

Status lifecycle:
  expected → checked_in → checked_out
  expected → late (after grace period)
  expected → absent (after checkin_window_end)
  expected → on_leave / holiday / weekend_off / unscheduled
"""

import uuid
from datetime import date, datetime
from typing import Optional

from sqlalchemy import Date, DateTime, ForeignKey, Numeric, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base, UUIDMixin


class ExpectedAttendance(Base, UUIDMixin):
    __tablename__ = "expected_attendance"
    __table_args__ = (
        UniqueConstraint(
            "employee_id",
            "shift_date",
            name="uq_expected_attendance_employee_shift_date",
        ),
    )

    # Employee context
    employee_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("employees.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    department_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("departments.id", ondelete="SET NULL"),
        nullable=True,
    )
    office_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("offices.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Shift context (snapshot at generation time)
    shift_template_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("shift_templates.id", ondelete="SET NULL"),
        nullable=True,
    )
    resolution_source: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="unscheduled",
        comment="override | assignment | department_rule | unscheduled",
    )

    # Temporal
    shift_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    expected_checkin: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    expected_checkout: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    checkin_window_start: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    checkin_window_end: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    checkout_window_start: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    checkout_window_end: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    # State machine
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="expected",
        comment="expected|checked_in|checked_out|late|absent|half_day|on_leave|holiday|weekend_off|overtime|incomplete|unscheduled",
    )

    # Actuals (populated as scans arrive)
    actual_checkin: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    actual_checkout: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    attendance_session_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("attendance_sessions.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Computed metrics
    late_minutes: Mapped[Optional[float]] = mapped_column(Numeric(6, 1), nullable=True, server_default="0")
    early_minutes: Mapped[Optional[float]] = mapped_column(Numeric(6, 1), nullable=True, server_default="0")
    overtime_minutes: Mapped[Optional[float]] = mapped_column(Numeric(6, 1), nullable=True, server_default="0")
    duration_minutes: Mapped[Optional[float]] = mapped_column(Numeric(8, 1), nullable=True)

    # Lifecycle
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )
    finalized_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    auto_generated: Mapped[bool] = mapped_column(nullable=False, server_default="true")
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<ExpectedAttendance(employee={self.employee_id}, "
            f"date={self.shift_date}, status={self.status})>"
        )
